name: StatusApp
options:
  bundleIdPrefix: com.statusapp
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  StatusApp:
    type: application
    platform: macOS
    sources:
      - path: StatusApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: StatusApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: StatusApp/StatusApp.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.statusapp.StatusApp
        PRODUCT_NAME: StatusApp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        ENABLE_PREVIEWS: YES
