name: StatusBar
options:
  bundleIdPrefix: com.statusbar
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  StatusBar:
    type: application
    platform: macOS
    sources:
      - path: StatusBar
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: StatusBar/StatusBar.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.statusapp.StatusBar
        PRODUCT_NAME: StatusBar
        MARKETING_VERSION: "1.2.0"
        CURRENT_PROJECT_VERSION: "1.2.0"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
    info:
      path: StatusBar/Info.plist
      properties:
        LSUIElement: true
